dist: xenial

language:
  - php
  - node_js

php:
  - "7.3"

install:
  - npm install

script:
  - npm run lint:all
  - npm run test:all

after_success:
  - npm run coverage

notifications:
  email: false

# Pull requests are built by default.
branches:
  only:
  - master

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
